# ============================================================================
# MergeMeter — Change Confidence Survey
# ============================================================================
#
# Copy this file to .github/workflows/mergemeter.yml in any repository
# you want to track with MergeMeter.
#
# Setup:
# 1. Add the following secrets to your GitHub repository
#    (Settings → Secrets and variables → Actions → New repository secret):
#
#      MERGEMETER_SECRET   — the HMAC signing secret from your MergeMeter dashboard
#      MERGEMETER_ORG_ID   — your MergeMeter organization ID
#
# 2. Commit this file. The next merged PR will trigger the action.
# ============================================================================

name: MergeMeter

on:
  pull_request:
    types: [closed]

jobs:
  mergemeter:
    name: MergeMeter — Change Confidence
    runs-on: ubuntu-latest

    # Only run when the PR was actually merged, not just closed
    if: github.event.pull_request.merged == true

    permissions:
      # Required to post the Change Confidence survey comment on the PR
      pull-requests: write

    steps:
      - name: Send to MergeMeter
        uses: bobbylough/mergemeter-action@main
        with:
          secret: ${{ secrets.MERGEMETER_SECRET }}
          org: ${{ secrets.MERGEMETER_ORG_ID }}
          # github-token defaults to the built-in GITHUB_TOKEN — no changes needed
